FROM openjdk:17-oracle

ARG TYPE

WORKDIR /app

COPY build/libs/code-aeron-concepts-tutorial.jar.jar aeron-concepts-cluster.jar

CMD ["java", "--add-opens", "java.base/sun.nio.ch=ALL-UNNAMED" ,"-cp", "aeron-concepts-cluster.jar", "com.weareadaptive.cluster.ClusterMain"]
