spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/auctionhouse
    username: testUsername
    password: testPassword
  jpa:
    #database-platform: org.hibernate.dialect
    hibernate:
      ddl-auto: validate
    show-sql: true

