FROM openjdk:17-oracle

ARG TYPE

WORKDIR /app

COPY build/libs/gateway-*-SNAPSHOT.jar aeron-gateway.jar

CMD ["java", "--add-opens", "java.base/sun.nio.ch=ALL-UNNAMED" ,"-cp", "aeron-gateway.jar", "com.weareadaptive.gateway.GatewayMain"]
