FROM openjdk:17-oracle

ARG TYPE

WORKDIR /app

COPY build/libs/basicClient-*-SNAPSHOT.jar aeron-client.jar

CMD ["java", "--add-opens", "java.base/sun.nio.ch=ALL-UNNAMED" ,"-cp", "aeron-client.jar", "com.weareadaptive.client.ClientMain"]
