version: '3.7'

x-config:
  cluster-addresses: &cluster-addresses
    # TODO make the number of nodes configurable
    CLUSTER_ADDRESSES: ${CLUSTER_ADDRESSES:-172.16.202.2,172.16.202.3,172.16.202.4}
  engine-env: &engine-env
    <<: *cluster-addresses
    HYDRA_CLUSTER_MODE: "TEST"
    RUNTIME_PARAMS: >-
      -Daeron.cluster.max.sessions=20
      -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5001

  health-check: &health-check
    healthcheck:
      test: [ "CMD-SHELL", "curl -fs http://localhost:8000/healthy || exit 1" ]
      interval: 1s
      timeout: 5s
      retries: 1
      start_period: 10s

services:
  engine0:
    image: "${PLATFORM_REGISTRY}hydra-chat-room-engine:latest"
    hostname: engine0
    shm_size: '1gb'
    networks:
      internal_bus:
        ipv4_address: 172.16.202.2
    restart: unless-stopped
    <<: *health-check
    environment:
      <<: *engine-env
  engine1:
    image: "${PLATFORM_REGISTRY}hydra-chat-room-engine:latest"
    hostname: engine1
    shm_size: '1gb'
    networks:
      internal_bus:
        ipv4_address: 172.16.202.3
    restart: unless-stopped
    <<: *health-check
    environment:
      <<: *engine-env

  engine2:
    image: "${PLATFORM_REGISTRY}hydra-chat-room-engine:latest"
    hostname: engine2
    shm_size: '1gb'
    networks:
      internal_bus:
        ipv4_address: 172.16.202.4
    restart: unless-stopped
    <<: *health-check
    environment:
      <<: *engine-env

  wg:
    image: "${PLATFORM_REGISTRY}hydra-chat-room-wg:latest"
    depends_on:
      - engine0
    hostname: gw
    shm_size: '1gb'
    ports:
      - 8929:8929
    networks:
      internal_bus:
        ipv4_address: 172.16.202.10
    restart: unless-stopped
    <<: *health-check
    environment:
      <<: *cluster-addresses
      RUNTIME_PARAMS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5001

  admin-ui:
    image: "${PLATFORM_REGISTRY}platform-admin-ui-box:latest"
    depends_on:
      - engine0
    hostname: admin-ui
    shm_size: '256mb'
    ports:
      - 3000:3000
    networks:
      internal_bus:
        ipv4_address: 172.16.202.100
    restart: unless-stopped

networks:
  internal_bus:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: 'true'
      com.docker.network.driver.mtu: 9000
      com.docker.network.enable_ipv6: 'false'
    ipam:
      driver: default
      config:
        - subnet: "172.16.202.0/24"
